version: '3.7'
services:
  php:
    container_name: multitenant_php
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/runtime/.config/composer:/var/www/.composer
      - ~/.ssh:/root/.ssh
      - .:/var/www/multitenant:cached
#      - /var/www/multitenant/node_modules # exclude node modules  => MAC optimization - disable it on linux
#      - /var/www/multitenant/vendor       # exclude vendors       => MAC optimization - disable it on linux
      - symfony_cache:/tmp/multitenant:rw
    working_dir: /var/www/multitenant
    networks:
      - default
    depends_on:
      - mysql
      - mongo
      - redis

  redis:
    container_name: multitenant_redis
    image: redis
    networks:
      - default

  mysql:
    container_name: multitenant_mysql
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/mariadb/collation.cnf:/etc/mysql/conf.d/collation.cnf
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    expose:
      - 3306
    ports:
      - 13306:3306
    networks:
      - default

  mongo:
    container_name: multitenant_mongo
    image: mongo:4.2
#    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./docker/db/mongo:/data/db
    expose:
      - 27017
    ports:
      - 27117:27017
    networks:
      - default

volumes:
  symfony_cache: